name: "Static Checks"
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - dev
  push:
    tags:
      - '*'

permissions:
   pull-requests: write

jobs:
  static-checks:
    name: Static Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: GDScript Toolkit Setup
        uses: Scony/godot-gdscript-toolkit@master
      - name: Linting
        run: gdlint .
      - name: Cyclomatic Complexity Check
        run: |
          ./cc_check.sh -c
          ./cc_check.sh
      - name: PR comment with file
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: ./cc_check_reports/report.json
